name: Netlify Preview Deployment
on:
  pull_request:
    branches:
      - main

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  Deploy-Preview-Shared:
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.3
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'pnpm'

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: false
          repository-cache: true

      - name: Install node modules
        run: pnpm install --frozen-lockfile

      - name: Install Netlify CLI
        run: pnpm add -g netlify-cli@17.23

      - name: Build Project Artifacts
        run: pnpm bazel build //adev:build

      - name: Deploy Project Artifacts to Netlify
        run: |
          echo "Calculating meaningful string as alias"
          ALIAS=$(node -e "console.log('${{github.run_id}} ${{github.event.number}} ${{github.event.pull_request.title}}'.replaceAll(' ','-').substring(0,37))")
          echo "Alias: $ALIAS"
            netlify deploy \
            --dir ./adev/dist/browser \
            --skip-functions-cache \
            --alias $ALIAS \
            --message "GH Action-${{env.BRANCH_NAME}}-${{github.event.number}}_${{github.event.pull_request.title}}" \
            --json \
            > ./deploy_output.json