name: Netlify Production Deployment

on:
  push:
    branches:
      - main

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.18.0
        with:
          bazelisk-cache: true
          repository-cache: true
          disk-cache: ${{ github.workflow }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Set environment variables from secrets and create .env file
        run: |
          echo "${{ vars.ENV_FILE }}" > .env

      - name: Build adev
        run: pnpm exec bazel build //adev:build --jobs=2 --local_ram_resources=5120

      - name: Prepare deploy directory
        run: |
          chmod -R u+w ./dist/bin/adev/dist/browser
          mv ./dist/bin/adev/dist/browser/index.csr.html ./dist/bin/adev/dist/browser/index.html
          cp ./_redirects ./dist/bin/adev/dist/browser/_redirects

      - name: Install Netlify CLI
        run: pnpm add -g netlify-cli@17.23

      - name: Deploy Project Artifacts to Netlify
        run: |
          netlify deploy \
            --site $NETLIFY_SITE_ID \
            --dir ./dist/bin/adev/dist/browser \
            --skip-functions-cache \
            --prod \
            --message "Action-${{ github.ref_name }}-${{ github.event.head_commit.message }}"
