name: Netlify Production Deployment

on:
  push:
    branches:
      - main
      - master

env:
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_TOKEN }}
  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

jobs:
  Deploy-Production-Shared:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.30.3 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Netlify CLI
        run: pnpm add -g netlify-cli@17.23

      - name: Create .env file
        run: echo "${{ vars.ENV_FILE }}" > .env

      - name: Build Project Artifacts
        run: pnpm docs:build


      - name: Deploy Project Artifacts to Netlify
        run: |
          netlify deploy \
            --dir ./adev/dist/browser \
            --skip-functions-cache \
            --prod \
            --message "Action-${{ github.ref_name }}-${{ github.event.head_commit.message }}"